Add initial implementation
gokrazy/selfupdate pull request #1
Opened 2023-02-19 11:28 UTC by damdo

This adds the initial implementation for the gokrazy selfupdate package.

2023-02-19 13:29 UTC, stapelberg requested changes

2023-02-19 13:29 UTC, stapelberg commented on config.go
> +// TODO: de-duplicate this with gokrazy.go into a gokrazy/internal package
Can you update the comment: doesn’t need to be gokrazy/internal, could even be useful for public packages

2023-02-19 13:29 UTC, stapelberg commented on go.mod
> +go 1.19
go 1.20?

2023-02-19 13:29 UTC, stapelberg commented on main.go
> +)
Can you move these into main()?

2023-02-19 13:29 UTC, stapelberg commented on main.go
> +
Can you move everything below into a `func selfupdate() error { …}`?

2023-02-19 13:29 UTC, stapelberg commented on main.go
> +	ticker := time.NewTicker(interval)
Can you add jitter in the range of a few seconds to minutes? https://github.com/gokrazy/gokrazy/blob/9cdaabefeec8cd194f0a14409f0b85f1c6217540/cmd/heartbeat/heartbeat.go#L133

2023-02-19 13:29 UTC, stapelberg commented on main.go
> +			}
Can you refactor this into a standalone function?

2023-02-19 13:29 UTC, stapelberg commented on selfupdate.go
> +	req.Header.Set("Content-Type", "text/json")
We should set both headers: Accept and Content-Type. 

The MIME type is application/json, not text/json

2023-02-19 13:29 UTC, stapelberg commented on selfupdate.go
> +			return fmt.Errorf("error fetching '%s' update from link '%s': %w", response.RegistryType, response.Link, err)
here and elsewhere: Use %q instead of '%s'

2023-02-19 13:29 UTC, stapelberg commented on selfupdate.go
> +		log.Fatalf("checking target partuuid support: %v", err)
Here and below: use return fmt.Errorf instead of log.Fatalf directly

2023-02-19 13:29 UTC, stapelberg commented on update_handlers.go
> +func httpHandler(response *updateResponse) (*zip.ReadCloser, io.ReadCloser, io.ReadCloser, io.ReadCloser, error) {
httpFetcher?

2023-02-19 13:29 UTC, stapelberg commented on update_handlers.go
> +	filePath := "/tmp/drive.zip"
Can you add a TODO for the location on disk (or on RAM)?

2023-02-19 13:29 UTC, stapelberg commented on update_handlers.go
> +	log.Printf("downloading update file from registry '%s' with url: %s", response.RegistryType, link)
Should we check for available disk space? Maybe leave a TODO

2023-02-19 13:29 UTC, stapelberg commented on update_handlers.go
> +	defer resp.Body.Close()
Check the resp.StatusCode to be HTTP 200 OK

2023-02-19 13:29 UTC, stapelberg commented on update_handlers.go
> +	return err
Check the error that file.Close() returns:

if err := out.Close(); err != nil {

2023-02-19 13:29 UTC, stapelberg commented on update_handlers.go
> +func httpHandler(response *updateResponse) (*zip.ReadCloser, io.ReadCloser, io.ReadCloser, io.ReadCloser, error) {
Maybe return a struct type instead of 4 different return values

2023-02-19 16:28 UTC, stapelberg requested changes

2023-02-19 16:28 UTC, stapelberg commented on main.go
> +			// If the updateProcess we exit with an error
missing “fails”

2023-02-19 16:28 UTC, stapelberg commented on main.go
> +		os.Exit(0)
return nil?

2023-02-19 16:28 UTC, stapelberg commented on main.go
> +			ticker.Stop()
return nil?

2023-02-19 16:28 UTC, stapelberg commented on main.go
> +	if shouldUpdate(response, sbomHash) {
inverse conditional:
if !shouldUpdate(…) {
return nil
}
// remaining logic

2023-02-19 16:28 UTC, stapelberg commented on selfupdate.go
> +	if resp.StatusCode != http.StatusOK {
defer resp.Body.Close() above line 44

2023-02-19 16:28 UTC, stapelberg commented on selfupdate.go
> +	uri := fmt.Sprintf("http://gokrazy:%s@127.0.0.1:%s/", httpPassword, httpPort)
Use “localhost”

2023-02-19 16:28 UTC, stapelberg commented on main.go
> +	flag.StringVar(&o.destinationDir, "destination_dir", "/tmp", "the destination directory for the fetched update file. default: /tmp")
Make the default /tmp/selfupdate

2023-02-19 16:28 UTC, stapelberg commented on update_handlers.go
> +		return rcs{},
remove linebreak

2023-02-19 16:28 UTC, stapelberg commented on update_handlers.go
> +	}
resp.StatusCode check?

2023-02-19 16:28 UTC, stapelberg commented on update_handlers.go
> +	availableDiskSpace, err := diskSpaceAvailable(destinationDir)
Move this into httpDownloadFile to save 1 HTTP request

2023-02-19 16:28 UTC, stapelberg commented on update_handlers.go
> +	if err := resp.Body.Close(); err != nil {
This should be out.Close(), not resp.Body.Close()

2023-02-19 16:28 UTC, stapelberg commented on update_handlers.go
> +	}
defer resp.Body.Close

2023-02-19 17:22 UTC, stapelberg requested changes

2023-02-19 17:22 UTC, stapelberg commented on update_handlers.go
> +	filePath := filepath.Join(destinationDir, "drive.gaf")
disk.gaf

2023-02-19 17:22 UTC, stapelberg commented on main.go
> -			loop = false
The loop variable can now be removed from the loop in line 87, too

2023-02-19 17:22 UTC, stapelberg commented on update_handlers.go
> +
remove blank line

2023-02-19 17:22 UTC, stapelberg commented on update_handlers.go
> +		return fmt.Errorf("unexpected status code received: %d", resp.StatusCode)
return fmt.Errorf("unexpected HTTP status code: %v", resp.Status)

2023-02-20 07:37 UTC, damdo commented
Feedback addressed and commits now squashed.

2023-02-20 07:38 UTC, damdo commented
Once this merges we need to change the default branch from init to main in the GH preferences.

2023-02-20 07:40 UTC, stapelberg approved these changes

2023-02-20 07:40 UTC, merged